version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin 591700125321.dkr.ecr.ca-central-1.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t webapp-test .
      - docker tag webapp-test:latest 591700125321.dkr.ecr.ca-central-1.amazonaws.com/webapp-test:latest

  post_build:
    commands:
      - echo Build completed. Pushing image...
      - docker push 591700125321.dkr.ecr.ca-central-1.amazonaws.com/webapp-test:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"webapp-test","imageUri":"591700125321.dkr.ecr.ca-central-1.amazonaws.com/webapp-test:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

